<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>acceuil</li>
                <li>produit</li>
                <li>contact</li>
            </ul>
        </nav>
    </header>
    <main>
        <?= $contenu ?>
    </main>
    <footer>
        <h3>ici le footer</h3>
    </footer>

</body>
</html>